In [10]:
import sqlite3
import pandas as pd

In [11]:
connection = sqlite3.connect("bike_store.db")
connection

In [12]:
# Example for one file
customers = pd.read_csv("C:/Users/Eric/Projects/DataAnalysisModule3/Week3/data/customers.csv")
customers.to_sql("customers", connection, if_exists="replace", index=False)
brands= pd.read_csv("C:/Users/Eric/Projects/DataAnalysisModule3/Week3/data/brands.csv")
brands.to_sql("brands", connection, if_exists="replace", index=False)
categories= pd.read_csv("C:/Users/Eric/Projects/DataAnalysisModule3/Week3/data/categories.csv")
categories.to_sql("categories", connection, if_exists="replace", index=False)
order_items= pd.read_csv("C:/Users/Eric/Projects/DataAnalysisModule3/Week3/data/order_items.csv")
order_items.to_sql("order_items", connection, if_exists="replace", index=False)
orders= pd.read_csv("C:/Users/Eric/Projects/DataAnalysisModule3/Week3/data/orders.csv")
orders.to_sql("orders", connection, if_exists="replace", index=False)
products= pd.read_csv("C:/Users/Eric/Projects/DataAnalysisModule3/Week3/data/products.csv")
products.to_sql("products", connection, if_exists="replace", index=False)
staffs= pd.read_csv("C:/Users/Eric/Projects/DataAnalysisModule3/Week3/data/staffs.csv")
staffs.to_sql("staffs", connection, if_exists="replace", index=False)
stocks= pd.read_csv("C:/Users/Eric/Projects/DataAnalysisModule3/Week3/data/stocks.csv")
stocks.to_sql("stocks", connection, if_exists="replace", index=False)
stores= pd.read_csv("C:/Users/Eric/Projects/DataAnalysisModule3/Week3/data/stores.csv")
stores.to_sql("stores", connection, if_exists="replace", index=False)

3

In [13]:
customers.head()

,customer_id,first_name,last_name,phone,email,street,city,state,zip_code
0,1,Debra,Burks,NaN,debra.burks@yahoo.com,9273 Thorne Ave.,Orchard Park,NY,14127
1,2,Kasha,Todd,NaN,kasha.todd@yahoo.com,910 Vine Street,Campbell,CA,95008
2,3,Tameka,Fisher,NaN,tameka.fisher@aol.com,769C Honey Creek St.,Redondo Beach,CA,90278
3,4,Daryl,Spence,NaN,daryl.spence@aol.com,988 Pearl Lane,Uniondale,NY,11553
4,5,Charolette,Rice,(916) 381-6003,charolette.rice@msn.com,107 River Dr.,Sacramento,CA,95820

In [14]:
pd.read_sql("SELECT name FROM sqlite_master WHERE type='table';", connection)

          name
0    customers
1       brands
2   categories
3  order_items
4       orders
5     products
6       staffs
7       stocks
8       stores

In [15]:
pd.read_sql("SELECT discount from order_items", connection)

      discount
0         0.20
1         0.07
2         0.05
3         0.05
4         0.20
...        ...
4717      0.07
4718      0.20
4719      0.20
4720      0.07
4721      0.20

[4722 rows x 1 columns]

In [16]:

# Your query here
query1 = "SELECT first_name,last_name,city FROM Customers"
pd.read_sql(query1, connection)

      first_name last_name           city
0          Debra     Burks   Orchard Park
1          Kasha      Todd       Campbell
2         Tameka    Fisher  Redondo Beach
3          Daryl    Spence      Uniondale
4     Charolette      Rice     Sacramento
...          ...       ...            ...
1440      Jamaal  Morrison  Staten Island
1441      Cassie     Cline       Brooklyn
1442      Lezlie      Lamb  Central Islip
1443      Ivette     Estes    Canandaigua
1444       Ester   Acevedo    San Lorenzo

[1445 rows x 3 columns]

In [17]:
products.head()

,product_id,product_name,brand_id,category_id,model_year,list_price
0,1,Trek 820 - 2016,9,6,2016,379.99
1,2,Ritchey Timberwolf Frameset - 2016,5,6,2016,749.99
2,3,Surly Wednesday Frameset - 2016,8,6,2016,999.99
3,4,Trek Fuel EX 8 29 - 2016,9,6,2016,2899.99
4,5,Heller Shagamaw Frame - 2016,3,6,2016,1320.99

In [18]:
# Your query here
query2 = "SELECT DISTINCT product_name,list_price from Products ORDER BY list_price DESC"
pd.read_sql(query2, connection)

                               product_name  list_price
0             Trek Domane SLR 9 Disc - 2018    11999.99
1             Trek Domane SLR 8 Disc - 2018     7499.99
2          Trek Silque SLR 8 Women's - 2017     6499.99
3            Trek Domane SL Frameset - 2018     6499.99
4    Trek Domane SL Frameset Women's - 2018     6499.99
..                                      ...         ...
286                    Trek Kickster - 2018      159.99
287         Trek Boy's Kickster - 2015/2017      149.99
288             Trek Girl's Kickster - 2017      149.99
289          Sun Bicycles Lil Kitt'n - 2017      109.99
290  Strider Classic 12 Balance Bike - 2018       89.99

[291 rows x 2 columns]

In [19]:
# Your query here
query3 = "SELECT first_name,last_name,city,state FROM Customers WHERE state = 'CA' ORDER BY last_name ASC"
pd.read_sql(query3, connection)

    first_name  last_name                    city state
0        Ester    Acevedo             San Lorenzo    CA
1       Jamaal     Albert                Torrance    CA
2        Sindy   Anderson                  Pomona    CA
3        Twana     Arnold                 Anaheim    CA
4       Selene     Austin                  Duarte    CA
..         ...        ...                     ...   ...
279     Darren       Witt               Coachella    CA
280       Lucy      Woods  Palos Verdes Peninsula    CA
281       Joel       Wynn               San Diego    CA
282      Yvone      Yates               San Pablo    CA
283      Ollie  Zimmerman                 Anaheim    CA

[284 rows x 4 columns]

In [20]:
# Your query here
query4 = "SELECT category_id,COUNT(product_id) as product_count FROM products GROUP BY category_id ORDER BY product_count DESC"
pd.read_sql(query4, connection)

   category_id  product_count
0            3             78
1            7             60
2            6             60
3            1             59
4            2             30
5            5             24
6            4             10

In [21]:
orders.head()

,order_id,customer_id,order_status,order_date,required_date,shipped_date,store_id,staff_id
0,1,259,4,2016-01-01,2016-01-03,2016-01-03,1,2
1,2,1212,4,2016-01-01,2016-01-04,2016-01-03,2,6
2,3,523,4,2016-01-02,2016-01-05,2016-01-03,2,7
3,4,175,4,2016-01-03,2016-01-04,2016-01-05,1,3
4,5,1324,4,2016-01-03,2016-01-06,2016-01-06,2,6

In [22]:
# Your query here
query5 = "SELECT order_id,order_date,customer_id from orders WHERE order_date LIKE '2018%' ORDER BY order_date asc"
pd.read_sql(query5, connection)

     order_id  order_date  customer_id
0        1324  2018-01-01          862
1        1325  2018-01-01           68
2        1326  2018-01-01          567
3        1327  2018-01-02         1026
4        1328  2018-01-02         1083
..        ...         ...          ...
287      1611  2018-09-06            6
288      1612  2018-10-21            3
289      1613  2018-11-18            1
290      1614  2018-11-28          135
291      1615  2018-12-28          136

[292 rows x 3 columns]

In [23]:
orders.head()

,order_id,customer_id,order_status,order_date,required_date,shipped_date,store_id,staff_id
0,1,259,4,2016-01-01,2016-01-03,2016-01-03,1,2
1,2,1212,4,2016-01-01,2016-01-04,2016-01-03,2,6
2,3,523,4,2016-01-02,2016-01-05,2016-01-03,2,7
3,4,175,4,2016-01-03,2016-01-04,2016-01-05,1,3
4,5,1324,4,2016-01-03,2016-01-06,2016-01-06,2,6

In [24]:
order_items.head()

   order_id  item_id  product_id  quantity  list_price  discount
0         1        1          20         1      599.99      0.20
1         1        2           8         2     1799.99      0.07
2         1        3          10         2     1549.00      0.05
3         1        4          16         2      599.99      0.05
4         1        5           4         1     2899.99      0.20

In [25]:
# Your query here
query6 = "SELECT o.order_id, SUM(oi.quantity) as quantity FROM orders o INNER JOIN order_items oi ON o.order_id = oi.order_id GROUP BY o.order_id"
pd.read_sql(query6, connection)

      order_id  quantity
0            1         8
1            2         3
2            3         2
3            4         2
4            5         4
...        ...       ...
1610      1611         4
1611      1612         8
1612      1613         3
1613      1614         5
1614      1615         4

[1615 rows x 2 columns]

In [26]:
stores.head()

,store_id,store_name,phone,email,street,city,state,zip_code
0,1,Santa Cruz Bikes,(831) 476-4321,santacruz@bikes.shop,3700 Portola Drive,Santa Cruz,CA,95060
1,2,Baldwin Bikes,(516) 379-8888,baldwin@bikes.shop,4200 Chestnut Lane,Baldwin,NY,11432
2,3,Rowlett Bikes,(972) 530-5555,rowlett@bikes.shop,8000 Fairway Avenue,Rowlett,TX,75088

In [35]:
# Your query here
query7 = """ 
select
s.store_name 
,SUM(oi.quantity*oi.list_price) as tot_rev

from orders o
join stores s on o.store_id = s.store_id
join order_items oi on o.order_id = oi.order_id
join products p on p.product_id = oi.product_id
group by s.store_name 

"""
pd.read_sql(query7, connection)

         store_name     tot_rev
0     Baldwin Bikes  5826242.21
1     Rowlett Bikes   962600.76
2  Santa Cruz Bikes  1790145.91

In [34]:
orders.head()

,order_id,customer_id,order_status,order_date,required_date,shipped_date,store_id,staff_id
0,1,259,4,2016-01-01,2016-01-03,2016-01-03,1,2
1,2,1212,4,2016-01-01,2016-01-04,2016-01-03,2,6
2,3,523,4,2016-01-02,2016-01-05,2016-01-03,2,7
3,4,175,4,2016-01-03,2016-01-04,2016-01-05,1,3
4,5,1324,4,2016-01-03,2016-01-06,2016-01-06,2,6

In [ ]:
# Your query here
query8 = """ 
select
c.first_name
,c.last_name
,sum(oi.quantity*p.price) as total_spend

from customers c 
join orders o on o.customer_id = c.customer_id
join order_items oi on oi.order_id = o.order_id
join products p on oi.product_id = p.product_id
group by c.first_name,c.last_name
order by total_spend desc
limit 5;

"""
pd.read_sql(query8, connection)

DatabaseError: Execution failed on sql '
select
c.first_name
,c.last_name
,sum(oi.quantity*p.price) as total_spend

from customers c
join orders o on o.customer_id = c.customer_id
join order_items oi on oi.order_id = o.order_id
join products p on oi.product_id = p.product_id
group by c.first_name,c.last_name
order by total_spend desc
limit 5;

': no such column: p.price

In [36]:
products.head()

,product_id,product_name,brand_id,category_id,model_year,list_price
0,1,Trek 820 - 2016,9,6,2016,379.99
1,2,Ritchey Timberwolf Frameset - 2016,5,6,2016,749.99
2,3,Surly Wednesday Frameset - 2016,8,6,2016,999.99
3,4,Trek Fuel EX 8 29 - 2016,9,6,2016,2899.99
4,5,Heller Shagamaw Frame - 2016,3,6,2016,1320.99

In [37]:
order_items.head()

   order_id  item_id  product_id  quantity  list_price  discount
0         1        1          20         1      599.99      0.20
1         1        2           8         2     1799.99      0.07
2         1        3          10         2     1549.00      0.05
3         1        4          16         2      599.99      0.05
4         1        5           4         1     2899.99      0.20

In [38]:
categories.head()

   category_id        category_name
0            1    Children Bicycles
1            2     Comfort Bicycles
2            3    Cruisers Bicycles
3            4  Cyclocross Bicycles
4            5       Electric Bikes

In [41]:
# Your query here
query9 = """ 

select
t.*
,row_number() over (partition by t.product_name order by t.quantity_sold) as rownum
from
(select
c.category_name
,p.product_name
,sum(oi.quantity) as quantity_sold
from products p 
join categories c on p.category_id = c.category_id
join order_items oi on oi.product_id = p.product_id
group by c.category_name, p.product_name
order by quantity_sold desc) as t
where rownum =1


"""
pd.read_sql(query9, connection)

DatabaseError: Execution failed on sql '

select
t.*
,row_number() over (partition by t.product_name order by t.quantity_sold) as rownum
from
(select
c.category_name
,p.product_name
,sum(oi.quantity) as quantity_sold
from products p
join categories c on p.category_id = c.category_id
join order_items oi on oi.product_id = p.product_id
group by c.category_name, p.product_name
order by quantity_sold desc) as t
where rownum =1


': misuse of aliased window function rownum

In [42]:
staffs.head()

,staff_id,first_name,last_name,email,phone,active,store_id,manager_id
0,1,Fabiola,Jackson,fabiola.jackson@bikes.shop,(831) 555-5554,1,1,NaN
1,2,Mireya,Copeland,mireya.copeland@bikes.shop,(831) 555-5555,1,1,1.0
2,3,Genna,Serrano,genna.serrano@bikes.shop,(831) 555-5556,1,1,2.0
3,4,Virgie,Wiggins,virgie.wiggins@bikes.shop,(831) 555-5557,1,1,2.0
4,5,Jannette,David,jannette.david@bikes.shop,(516) 379-4444,1,2,1.0

In [43]:
orders.head()

,order_id,customer_id,order_status,order_date,required_date,shipped_date,store_id,staff_id
0,1,259,4,2016-01-01,2016-01-03,2016-01-03,1,2
1,2,1212,4,2016-01-01,2016-01-04,2016-01-03,2,6
2,3,523,4,2016-01-02,2016-01-05,2016-01-03,2,7
3,4,175,4,2016-01-03,2016-01-04,2016-01-05,1,3
4,5,1324,4,2016-01-03,2016-01-06,2016-01-06,2,6

In [45]:
# Your query here
query10 = """ 
select
s.staff_id
,s.first_name
,s.last_name
,Count(order_id) as order_count

from staffs s
join orders o on o.staff_id = s.staff_id
group by s.staff_id, s.first_name, s.last_name
order by order_count desc
"""
pd.read_sql(query10, connection)

   staff_id first_name last_name  order_count
0         6  Marcelene     Boyer          553
1         7     Venita    Daniel          540
2         3      Genna   Serrano          184
3         2     Mireya  Copeland          164
4         8       Kali    Vargas           88
5         9      Layla   Terrell           86